# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Static Coineko CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run test && npm run build
      - run: cp ./dist/index.html ./dist/200.html
      - name: Deploy to coineko surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "coineko.surge.sh"
          project: "./dist/"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}